package net.kaaass.zerotierfix.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "APP_NODE".
*/
public class AppNodeDao extends AbstractDao<AppNode, Long> {

    public static final String TABLENAME = "APP_NODE";

    /**
     * Properties of entity AppNode.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property NodeId = new Property(0, Long.class, "nodeId", true, "_id");
        public final static Property NodeIdStr = new Property(1, String.class, "nodeIdStr", false, "NODE_ID_STR");
    }


    public AppNodeDao(DaoConfig config) {
        super(config);
    }
    
    public AppNodeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APP_NODE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: nodeId
                "\"NODE_ID_STR\" TEXT);"); // 1: nodeIdStr
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APP_NODE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppNode entity) {
        stmt.clearBindings();
 
        Long nodeId = entity.getNodeId();
        if (nodeId != null) {
            stmt.bindLong(1, nodeId);
        }
 
        String nodeIdStr = entity.getNodeIdStr();
        if (nodeIdStr != null) {
            stmt.bindString(2, nodeIdStr);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppNode entity) {
        stmt.clearBindings();
 
        Long nodeId = entity.getNodeId();
        if (nodeId != null) {
            stmt.bindLong(1, nodeId);
        }
 
        String nodeIdStr = entity.getNodeIdStr();
        if (nodeIdStr != null) {
            stmt.bindString(2, nodeIdStr);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AppNode readEntity(Cursor cursor, int offset) {
        AppNode entity = new AppNode( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // nodeId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // nodeIdStr
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppNode entity, int offset) {
        entity.setNodeId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNodeIdStr(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AppNode entity, long rowId) {
        entity.setNodeId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AppNode entity) {
        if(entity != null) {
            return entity.getNodeId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AppNode entity) {
        return entity.getNodeId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
