package net.kaaass.zerotierfix.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import net.kaaass.zerotierfix.model.AssignedAddress.AddressType;
import net.kaaass.zerotierfix.model.AssignedAddress.AddressTypeConverter;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ASSIGNED_ADDRESS".
*/
public class AssignedAddressDao extends AbstractDao<AssignedAddress, Long> {

    public static final String TABLENAME = "ASSIGNED_ADDRESS";

    /**
     * Properties of entity AssignedAddress.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NetworkId = new Property(1, long.class, "networkId", false, "NETWORK_ID");
        public final static Property Type = new Property(2, Integer.class, "type", false, "TYPE");
        public final static Property AddressBytes = new Property(3, byte[].class, "addressBytes", false, "ADDRESS_BYTES");
        public final static Property AddressString = new Property(4, String.class, "addressString", false, "ADDRESS_STRING");
        public final static Property Prefix = new Property(5, short.class, "prefix", false, "PREFIX");
    }

    private final AddressTypeConverter typeConverter = new AddressTypeConverter();
    private Query<AssignedAddress> networkConfig_AssignedAddressesQuery;

    public AssignedAddressDao(DaoConfig config) {
        super(config);
    }
    
    public AssignedAddressDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ASSIGNED_ADDRESS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NETWORK_ID\" INTEGER NOT NULL ," + // 1: networkId
                "\"TYPE\" INTEGER," + // 2: type
                "\"ADDRESS_BYTES\" BLOB," + // 3: addressBytes
                "\"ADDRESS_STRING\" TEXT," + // 4: addressString
                "\"PREFIX\" INTEGER NOT NULL );"); // 5: prefix
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ASSIGNED_ADDRESS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AssignedAddress entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNetworkId());
 
        AddressType type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, typeConverter.convertToDatabaseValue(type));
        }
 
        byte[] addressBytes = entity.getAddressBytes();
        if (addressBytes != null) {
            stmt.bindBlob(4, addressBytes);
        }
 
        String addressString = entity.getAddressString();
        if (addressString != null) {
            stmt.bindString(5, addressString);
        }
        stmt.bindLong(6, entity.getPrefix());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AssignedAddress entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNetworkId());
 
        AddressType type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, typeConverter.convertToDatabaseValue(type));
        }
 
        byte[] addressBytes = entity.getAddressBytes();
        if (addressBytes != null) {
            stmt.bindBlob(4, addressBytes);
        }
 
        String addressString = entity.getAddressString();
        if (addressString != null) {
            stmt.bindString(5, addressString);
        }
        stmt.bindLong(6, entity.getPrefix());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AssignedAddress readEntity(Cursor cursor, int offset) {
        AssignedAddress entity = new AssignedAddress( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // networkId
            cursor.isNull(offset + 2) ? null : typeConverter.convertToEntityProperty(cursor.getInt(offset + 2)), // type
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // addressBytes
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // addressString
            cursor.getShort(offset + 5) // prefix
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AssignedAddress entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNetworkId(cursor.getLong(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : typeConverter.convertToEntityProperty(cursor.getInt(offset + 2)));
        entity.setAddressBytes(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setAddressString(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPrefix(cursor.getShort(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AssignedAddress entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AssignedAddress entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AssignedAddress entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "assignedAddresses" to-many relationship of NetworkConfig. */
    public List<AssignedAddress> _queryNetworkConfig_AssignedAddresses(long networkId) {
        synchronized (this) {
            if (networkConfig_AssignedAddressesQuery == null) {
                QueryBuilder<AssignedAddress> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.NetworkId.eq(null));
                networkConfig_AssignedAddressesQuery = queryBuilder.build();
            }
        }
        Query<AssignedAddress> query = networkConfig_AssignedAddressesQuery.forCurrentThread();
        query.setParameter(0, networkId);
        return query.list();
    }

}
