package net.kaaass.zerotierfix.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.kaaass.zerotierfix.model.AppNode;
import net.kaaass.zerotierfix.model.AssignedAddress;
import net.kaaass.zerotierfix.model.DnsServer;
import net.kaaass.zerotierfix.model.MoonOrbit;
import net.kaaass.zerotierfix.model.Network;
import net.kaaass.zerotierfix.model.NetworkConfig;

import net.kaaass.zerotierfix.model.AppNodeDao;
import net.kaaass.zerotierfix.model.AssignedAddressDao;
import net.kaaass.zerotierfix.model.DnsServerDao;
import net.kaaass.zerotierfix.model.MoonOrbitDao;
import net.kaaass.zerotierfix.model.NetworkDao;
import net.kaaass.zerotierfix.model.NetworkConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appNodeDaoConfig;
    private final DaoConfig assignedAddressDaoConfig;
    private final DaoConfig dnsServerDaoConfig;
    private final DaoConfig moonOrbitDaoConfig;
    private final DaoConfig networkDaoConfig;
    private final DaoConfig networkConfigDaoConfig;

    private final AppNodeDao appNodeDao;
    private final AssignedAddressDao assignedAddressDao;
    private final DnsServerDao dnsServerDao;
    private final MoonOrbitDao moonOrbitDao;
    private final NetworkDao networkDao;
    private final NetworkConfigDao networkConfigDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appNodeDaoConfig = daoConfigMap.get(AppNodeDao.class).clone();
        appNodeDaoConfig.initIdentityScope(type);

        assignedAddressDaoConfig = daoConfigMap.get(AssignedAddressDao.class).clone();
        assignedAddressDaoConfig.initIdentityScope(type);

        dnsServerDaoConfig = daoConfigMap.get(DnsServerDao.class).clone();
        dnsServerDaoConfig.initIdentityScope(type);

        moonOrbitDaoConfig = daoConfigMap.get(MoonOrbitDao.class).clone();
        moonOrbitDaoConfig.initIdentityScope(type);

        networkDaoConfig = daoConfigMap.get(NetworkDao.class).clone();
        networkDaoConfig.initIdentityScope(type);

        networkConfigDaoConfig = daoConfigMap.get(NetworkConfigDao.class).clone();
        networkConfigDaoConfig.initIdentityScope(type);

        appNodeDao = new AppNodeDao(appNodeDaoConfig, this);
        assignedAddressDao = new AssignedAddressDao(assignedAddressDaoConfig, this);
        dnsServerDao = new DnsServerDao(dnsServerDaoConfig, this);
        moonOrbitDao = new MoonOrbitDao(moonOrbitDaoConfig, this);
        networkDao = new NetworkDao(networkDaoConfig, this);
        networkConfigDao = new NetworkConfigDao(networkConfigDaoConfig, this);

        registerDao(AppNode.class, appNodeDao);
        registerDao(AssignedAddress.class, assignedAddressDao);
        registerDao(DnsServer.class, dnsServerDao);
        registerDao(MoonOrbit.class, moonOrbitDao);
        registerDao(Network.class, networkDao);
        registerDao(NetworkConfig.class, networkConfigDao);
    }
    
    public void clear() {
        appNodeDaoConfig.clearIdentityScope();
        assignedAddressDaoConfig.clearIdentityScope();
        dnsServerDaoConfig.clearIdentityScope();
        moonOrbitDaoConfig.clearIdentityScope();
        networkDaoConfig.clearIdentityScope();
        networkConfigDaoConfig.clearIdentityScope();
    }

    public AppNodeDao getAppNodeDao() {
        return appNodeDao;
    }

    public AssignedAddressDao getAssignedAddressDao() {
        return assignedAddressDao;
    }

    public DnsServerDao getDnsServerDao() {
        return dnsServerDao;
    }

    public MoonOrbitDao getMoonOrbitDao() {
        return moonOrbitDao;
    }

    public NetworkDao getNetworkDao() {
        return networkDao;
    }

    public NetworkConfigDao getNetworkConfigDao() {
        return networkConfigDao;
    }

}
