package net.kaaass.zerotierfix.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DNS_SERVER".
*/
public class DnsServerDao extends AbstractDao<DnsServer, Long> {

    public static final String TABLENAME = "DNS_SERVER";

    /**
     * Properties of entity DnsServer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NetworkId = new Property(1, Long.class, "networkId", false, "NETWORK_ID");
        public final static Property Nameserver = new Property(2, String.class, "nameserver", false, "NAMESERVER");
    }

    private Query<DnsServer> networkConfig_DnsServersQuery;

    public DnsServerDao(DaoConfig config) {
        super(config);
    }
    
    public DnsServerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DNS_SERVER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NETWORK_ID\" INTEGER," + // 1: networkId
                "\"NAMESERVER\" TEXT);"); // 2: nameserver
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DNS_SERVER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DnsServer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long networkId = entity.getNetworkId();
        if (networkId != null) {
            stmt.bindLong(2, networkId);
        }
 
        String nameserver = entity.getNameserver();
        if (nameserver != null) {
            stmt.bindString(3, nameserver);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DnsServer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long networkId = entity.getNetworkId();
        if (networkId != null) {
            stmt.bindLong(2, networkId);
        }
 
        String nameserver = entity.getNameserver();
        if (nameserver != null) {
            stmt.bindString(3, nameserver);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DnsServer readEntity(Cursor cursor, int offset) {
        DnsServer entity = new DnsServer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // networkId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // nameserver
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DnsServer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNetworkId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setNameserver(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DnsServer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DnsServer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DnsServer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dnsServers" to-many relationship of NetworkConfig. */
    public List<DnsServer> _queryNetworkConfig_DnsServers(Long networkId) {
        synchronized (this) {
            if (networkConfig_DnsServersQuery == null) {
                QueryBuilder<DnsServer> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.NetworkId.eq(null));
                networkConfig_DnsServersQuery = queryBuilder.build();
            }
        }
        Query<DnsServer> query = networkConfig_DnsServersQuery.forCurrentThread();
        query.setParameter(0, networkId);
        return query.list();
    }

}
