package net.kaaass.zerotierfix.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOON_ORBIT".
*/
public class MoonOrbitDao extends AbstractDao<MoonOrbit, Long> {

    public static final String TABLENAME = "MOON_ORBIT";

    /**
     * Properties of entity MoonOrbit.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MoonWorldId = new Property(0, Long.class, "moonWorldId", true, "_id");
        public final static Property MoonSeed = new Property(1, Long.class, "moonSeed", false, "MOON_SEED");
        public final static Property FromFile = new Property(2, boolean.class, "fromFile", false, "FROM_FILE");
    }


    public MoonOrbitDao(DaoConfig config) {
        super(config);
    }
    
    public MoonOrbitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOON_ORBIT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: moonWorldId
                "\"MOON_SEED\" INTEGER," + // 1: moonSeed
                "\"FROM_FILE\" INTEGER NOT NULL );"); // 2: fromFile
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOON_ORBIT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MoonOrbit entity) {
        stmt.clearBindings();
 
        Long moonWorldId = entity.getMoonWorldId();
        if (moonWorldId != null) {
            stmt.bindLong(1, moonWorldId);
        }
 
        Long moonSeed = entity.getMoonSeed();
        if (moonSeed != null) {
            stmt.bindLong(2, moonSeed);
        }
        stmt.bindLong(3, entity.getFromFile() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MoonOrbit entity) {
        stmt.clearBindings();
 
        Long moonWorldId = entity.getMoonWorldId();
        if (moonWorldId != null) {
            stmt.bindLong(1, moonWorldId);
        }
 
        Long moonSeed = entity.getMoonSeed();
        if (moonSeed != null) {
            stmt.bindLong(2, moonSeed);
        }
        stmt.bindLong(3, entity.getFromFile() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MoonOrbit readEntity(Cursor cursor, int offset) {
        MoonOrbit entity = new MoonOrbit( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // moonWorldId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // moonSeed
            cursor.getShort(offset + 2) != 0 // fromFile
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MoonOrbit entity, int offset) {
        entity.setMoonWorldId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMoonSeed(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setFromFile(cursor.getShort(offset + 2) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MoonOrbit entity, long rowId) {
        entity.setMoonWorldId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MoonOrbit entity) {
        if(entity != null) {
            return entity.getMoonWorldId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MoonOrbit entity) {
        return entity.getMoonWorldId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
