package net.kaaass.zerotierfix.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import net.kaaass.zerotierfix.model.NetworkConfig.NetworkStatusConverter;
import net.kaaass.zerotierfix.model.NetworkConfig.NetworkTypeConverter;
import net.kaaass.zerotierfix.model.type.NetworkStatus;
import net.kaaass.zerotierfix.model.type.NetworkType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NETWORK_CONFIG".
*/
public class NetworkConfigDao extends AbstractDao<NetworkConfig, Long> {

    public static final String TABLENAME = "NETWORK_CONFIG";

    /**
     * Properties of entity NetworkConfig.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, Integer.class, "type", false, "TYPE");
        public final static Property Status = new Property(2, Integer.class, "status", false, "STATUS");
        public final static Property Mac = new Property(3, String.class, "mac", false, "MAC");
        public final static Property Mtu = new Property(4, String.class, "mtu", false, "MTU");
        public final static Property Broadcast = new Property(5, boolean.class, "broadcast", false, "BROADCAST");
        public final static Property Bridging = new Property(6, boolean.class, "bridging", false, "BRIDGING");
        public final static Property RouteViaZeroTier = new Property(7, boolean.class, "routeViaZeroTier", false, "ROUTE_VIA_ZERO_TIER");
        public final static Property UseCustomDNS = new Property(8, boolean.class, "useCustomDNS", false, "USE_CUSTOM_DNS");
        public final static Property DnsMode = new Property(9, int.class, "dnsMode", false, "DNS_MODE");
    }

    private DaoSession daoSession;

    private final NetworkTypeConverter typeConverter = new NetworkTypeConverter();
    private final NetworkStatusConverter statusConverter = new NetworkStatusConverter();

    public NetworkConfigDao(DaoConfig config) {
        super(config);
    }
    
    public NetworkConfigDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NETWORK_CONFIG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TYPE\" INTEGER," + // 1: type
                "\"STATUS\" INTEGER," + // 2: status
                "\"MAC\" TEXT," + // 3: mac
                "\"MTU\" TEXT," + // 4: mtu
                "\"BROADCAST\" INTEGER NOT NULL ," + // 5: broadcast
                "\"BRIDGING\" INTEGER NOT NULL ," + // 6: bridging
                "\"ROUTE_VIA_ZERO_TIER\" INTEGER NOT NULL ," + // 7: routeViaZeroTier
                "\"USE_CUSTOM_DNS\" INTEGER NOT NULL ," + // 8: useCustomDNS
                "\"DNS_MODE\" INTEGER NOT NULL );"); // 9: dnsMode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NETWORK_CONFIG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NetworkConfig entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        NetworkType type = entity.getType();
        if (type != null) {
            stmt.bindLong(2, typeConverter.convertToDatabaseValue(type));
        }
 
        NetworkStatus status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(3, statusConverter.convertToDatabaseValue(status));
        }
 
        String mac = entity.getMac();
        if (mac != null) {
            stmt.bindString(4, mac);
        }
 
        String mtu = entity.getMtu();
        if (mtu != null) {
            stmt.bindString(5, mtu);
        }
        stmt.bindLong(6, entity.getBroadcast() ? 1L: 0L);
        stmt.bindLong(7, entity.getBridging() ? 1L: 0L);
        stmt.bindLong(8, entity.getRouteViaZeroTier() ? 1L: 0L);
        stmt.bindLong(9, entity.getUseCustomDNS() ? 1L: 0L);
        stmt.bindLong(10, entity.getDnsMode());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NetworkConfig entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        NetworkType type = entity.getType();
        if (type != null) {
            stmt.bindLong(2, typeConverter.convertToDatabaseValue(type));
        }
 
        NetworkStatus status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(3, statusConverter.convertToDatabaseValue(status));
        }
 
        String mac = entity.getMac();
        if (mac != null) {
            stmt.bindString(4, mac);
        }
 
        String mtu = entity.getMtu();
        if (mtu != null) {
            stmt.bindString(5, mtu);
        }
        stmt.bindLong(6, entity.getBroadcast() ? 1L: 0L);
        stmt.bindLong(7, entity.getBridging() ? 1L: 0L);
        stmt.bindLong(8, entity.getRouteViaZeroTier() ? 1L: 0L);
        stmt.bindLong(9, entity.getUseCustomDNS() ? 1L: 0L);
        stmt.bindLong(10, entity.getDnsMode());
    }

    @Override
    protected final void attachEntity(NetworkConfig entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NetworkConfig readEntity(Cursor cursor, int offset) {
        NetworkConfig entity = new NetworkConfig( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : typeConverter.convertToEntityProperty(cursor.getInt(offset + 1)), // type
            cursor.isNull(offset + 2) ? null : statusConverter.convertToEntityProperty(cursor.getInt(offset + 2)), // status
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mac
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mtu
            cursor.getShort(offset + 5) != 0, // broadcast
            cursor.getShort(offset + 6) != 0, // bridging
            cursor.getShort(offset + 7) != 0, // routeViaZeroTier
            cursor.getShort(offset + 8) != 0, // useCustomDNS
            cursor.getInt(offset + 9) // dnsMode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NetworkConfig entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : typeConverter.convertToEntityProperty(cursor.getInt(offset + 1)));
        entity.setStatus(cursor.isNull(offset + 2) ? null : statusConverter.convertToEntityProperty(cursor.getInt(offset + 2)));
        entity.setMac(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMtu(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBroadcast(cursor.getShort(offset + 5) != 0);
        entity.setBridging(cursor.getShort(offset + 6) != 0);
        entity.setRouteViaZeroTier(cursor.getShort(offset + 7) != 0);
        entity.setUseCustomDNS(cursor.getShort(offset + 8) != 0);
        entity.setDnsMode(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NetworkConfig entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NetworkConfig entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NetworkConfig entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
