package net.kaaass.zerotierfix.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NETWORK".
*/
public class NetworkDao extends AbstractDao<Network, Long> {

    public static final String TABLENAME = "NETWORK";

    /**
     * Properties of entity Network.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property NetworkId = new Property(0, Long.class, "networkId", true, "_id");
        public final static Property NetworkIdStr = new Property(1, String.class, "networkIdStr", false, "NETWORK_ID_STR");
        public final static Property NetworkName = new Property(2, String.class, "networkName", false, "NETWORK_NAME");
        public final static Property UseDefaultRoute = new Property(3, boolean.class, "useDefaultRoute", false, "USE_DEFAULT_ROUTE");
        public final static Property LastActivated = new Property(4, boolean.class, "lastActivated", false, "LAST_ACTIVATED");
        public final static Property NetworkConfigId = new Property(5, long.class, "networkConfigId", false, "NETWORK_CONFIG_ID");
    }

    private DaoSession daoSession;


    public NetworkDao(DaoConfig config) {
        super(config);
    }
    
    public NetworkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NETWORK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: networkId
                "\"NETWORK_ID_STR\" TEXT," + // 1: networkIdStr
                "\"NETWORK_NAME\" TEXT," + // 2: networkName
                "\"USE_DEFAULT_ROUTE\" INTEGER NOT NULL ," + // 3: useDefaultRoute
                "\"LAST_ACTIVATED\" INTEGER NOT NULL ," + // 4: lastActivated
                "\"NETWORK_CONFIG_ID\" INTEGER NOT NULL );"); // 5: networkConfigId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NETWORK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Network entity) {
        stmt.clearBindings();
 
        Long networkId = entity.getNetworkId();
        if (networkId != null) {
            stmt.bindLong(1, networkId);
        }
 
        String networkIdStr = entity.getNetworkIdStr();
        if (networkIdStr != null) {
            stmt.bindString(2, networkIdStr);
        }
 
        String networkName = entity.getNetworkName();
        if (networkName != null) {
            stmt.bindString(3, networkName);
        }
        stmt.bindLong(4, entity.getUseDefaultRoute() ? 1L: 0L);
        stmt.bindLong(5, entity.getLastActivated() ? 1L: 0L);
        stmt.bindLong(6, entity.getNetworkConfigId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Network entity) {
        stmt.clearBindings();
 
        Long networkId = entity.getNetworkId();
        if (networkId != null) {
            stmt.bindLong(1, networkId);
        }
 
        String networkIdStr = entity.getNetworkIdStr();
        if (networkIdStr != null) {
            stmt.bindString(2, networkIdStr);
        }
 
        String networkName = entity.getNetworkName();
        if (networkName != null) {
            stmt.bindString(3, networkName);
        }
        stmt.bindLong(4, entity.getUseDefaultRoute() ? 1L: 0L);
        stmt.bindLong(5, entity.getLastActivated() ? 1L: 0L);
        stmt.bindLong(6, entity.getNetworkConfigId());
    }

    @Override
    protected final void attachEntity(Network entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Network readEntity(Cursor cursor, int offset) {
        Network entity = new Network( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // networkId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // networkIdStr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // networkName
            cursor.getShort(offset + 3) != 0, // useDefaultRoute
            cursor.getShort(offset + 4) != 0, // lastActivated
            cursor.getLong(offset + 5) // networkConfigId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Network entity, int offset) {
        entity.setNetworkId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNetworkIdStr(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNetworkName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUseDefaultRoute(cursor.getShort(offset + 3) != 0);
        entity.setLastActivated(cursor.getShort(offset + 4) != 0);
        entity.setNetworkConfigId(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Network entity, long rowId) {
        entity.setNetworkId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Network entity) {
        if(entity != null) {
            return entity.getNetworkId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Network entity) {
        return entity.getNetworkId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getNetworkConfigDao().getAllColumns());
            builder.append(" FROM NETWORK T");
            builder.append(" LEFT JOIN NETWORK_CONFIG T0 ON T.\"NETWORK_CONFIG_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Network loadCurrentDeep(Cursor cursor, boolean lock) {
        Network entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        NetworkConfig networkConfig = loadCurrentOther(daoSession.getNetworkConfigDao(), cursor, offset);
         if(networkConfig != null) {
            entity.setNetworkConfig(networkConfig);
        }

        return entity;    
    }

    public Network loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Network> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Network> list = new ArrayList<Network>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Network> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Network> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
